# Generated by Django 4.2.7 on 2023-11-07 09:34

import autoservice.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Automobilio_modelis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marke', models.CharField(max_length=30, verbose_name='Markė')),
                ('modelis', models.CharField(max_length=50, verbose_name='Modelis')),
            ],
        ),
        migrations.CreateModel(
            name='Automobilis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valstybinis_nr', models.CharField(help_text='Įvestas automobilio numeris turi turėti bent vieną skaičių.', max_length=6, validators=[autoservice.models.validate_at_least_one_digit], verbose_name='Valstybinis_NR')),
                ('vin_kodas', models.CharField(help_text='Įveskite automobilio VIN kodą', max_length=17, verbose_name='VIN_kodas')),
                ('klientas', models.CharField(help_text='Įveskite aptarnaujamo žmogaus vardą pavardę', max_length=200, verbose_name='Klientas')),
                ('automobilio_modelis_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='autoservice.automobilio_modelis')),
            ],
        ),
        migrations.CreateModel(
            name='Paslauga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pavadinimas', models.CharField(help_text='Įveskite paslaugos pavadinimą', max_length=200, verbose_name='Pavadinimas')),
                ('kaina', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Uzsakymas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True, verbose_name='Data')),
                ('automobilis_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='autoservice.automobilis')),
                ('paslauga', models.ManyToManyField(help_text='Pasirinkite norimas paslaugas', to='autoservice.paslauga')),
            ],
        ),
    ]
