# Generated by Django 4.2.7 on 2023-11-09 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0004_alter_automobilio_modelis_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uzsakymas',
            name='status',
            field=models.CharField(blank=True, choices=[('r', 'Rezervuota'), ('a', 'Atšaukta'), ('t', 'Atlikta'), ('v', 'Vykdoma')], default='', help_text='Statusas', max_length=1),
        ),
    ]
