# Generated by Django 4.2.7 on 2023-11-13 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0007_alter_automobilis_nuotrauka'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automobilis',
            name='nuotrauka',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Mašina'),
        ),
    ]
